export const ACCOUNT_REPOSITORY = Symbol('ACCOUNT_REPOSITORY');
export const ACCOUNT_HISTORY_REPOSITORY = Symbol('ACCOUNT_HISTORY_REPOSITORY');
export const ACCOUNT_PARAMS_REPOSITORY = Symbol('ACCOUNT_PARAMS_REPOSITORY');
